### ISSUE TITLE
Combine?

### ISSUE THREAD

**Issue by jbis9051** [JRProgramming/Blind-Brook-Block-Schedule-Generator#5]
Hi, I am Josh Brown (Junior at BB).

I also created a schedule generator.

https://bbscheduler.com
https://github.com/jbis9051/BB-Calendar-Creator

My generator creates a printable HTML table as well as an iCal file containing all classes as events for every school day that can be imported into any calendar application such as iOS Calendar, macOS Calendar, Google Calendar, etc.

I was wondering if you would like to combine our projects?

**Comment by JRProgramming** [comment]
Hey, 

We are in the same gym class.

Let’s talk there.

By the way, did you purchase the domain? That’s neat.

-Johnny Ramirez

**Comment by jbis9051** [comment]
Sure. 

Yes. http://namecheap.com/ sells them for really cheap. I think that one costed ~$10 a year.

**Comment by JRProgramming** [comment]
Hey,

I thought about your proposal for combining. At this point, everyone got their scheduled printed/figured out so there’s not going to be as much activity until next year. 

I checked out your site, and I came to the conclusion that our sites both function very similarly. We both have our strengths and weaknesses; you can download the calendar but printing portrait (not landscape)  doesn’t work well for you, while I don’t have the function to download schedules (maybe soon)

I am very interested on how you would like to “combine” the sites. Our websites are pretty similar, so I don’t see how there’s going to be that much of a difference. The other option that I’m more interested in is buying your site because next year, the majority of the high school would be using my site based on what is being presented at orientation (current eighth graders, current freshman, and current sophomore will probably use mine, while the current juniors might use yours). I want to acknowledge the amount of work you have been putting in, so therefore I’m thinking of paying more than 30 dollars to buy the domain and the site. If I were you, I would be happy to get free money. Let me know soon what you think and hopefully we can work something out.

**Comment by jbis9051** [comment]
I understand most people have figured out their schedule for this year, however I was thinking for future school years. 

If you see an issue with printing portrait please [open an issue on GitHub](https://github.com/jbis9051/Blind-Brook-Calendar-Creator/issues/new), I don't see any problems. The times are a bit squished, but that can be fixed easily.

By combine, I meant that we could take some aspects of your site (like the coloring, client side html generation, teachers name) and some aspects of my site (design, domain, manual class entering, more stable importing, etc.) and combine those ideas. I think if we work together the end product will be better than us working alone.

Functionality wise, our sites have some similarities (the most obvious being that we can both import from eSchoolData via copy & paste and generate a HTML table with the schedule) however many things differ. I could talk about different aspects of my site that in my opinion make it work better and more scalable, but I am not attempting to compete with your site or with you. I thought that we could combine our projects to create the best possible scheduler for BB students which for me is the goal.

Were you interested in purchasing the domain or the entire site? My site is completely open source under the [MIT License](https://github.com/jbis9051/Blind-Brook-Calendar-Creator/blob/master/LICENSE). You can read the [license](https://github.com/jbis9051/Blind-Brook-Calendar-Creator/blob/master/LICENSE) to find out exactly what you can do but you are definitely able to use the code without paying for it (under some restrictions). However, the site requires a server and it runs `Node.js` with `express` and many other modules.  From your other projects on Github, it doesn't seem like you have experience with those technologies so it might be hard for you to change and edit the site. Which is another reason why I think combing is a good idea. Both our expertise in different things can contribute.

If I wanted to just give you the site and domain then I would just give it you for free, but thats not what I would like to do. I still see combining as the best option. However, if you would not like to that, then thats your choice.

**Comment by jbis9051** [comment]
If you are still interested:

Evidently, more people use your site. That can most likely be attributed to your link being included in the orientation presentations at the school. However, I suggest we use my site as a code starting point. This is for a couple reasons. Firstly, it has an easily rememberable domain (bbscheduler.com). But most importantly, much less has to be done to take your ideas and features and add them to my site than to take my ideas and features and add them to your site. Additionally, mine runs off of a server I control so we can do things backend that we couldn't do on your site. 

My suggestion is that you list out some features of your site that my site doesn't have (like the coloring) and other ideas that you have but may have not been implemented. We can discuss implementing them on our combined site. You can write the code to implement them. If you need help or confused about anything I can try to help and explain to you. Then we can redirect your site to our new one (may have to do this with JS cause we can't send headers and we don't have access to the DNS records) and tell the school to use the new domain in presentations. Your commit history will show your work and you will be added to the about section and copyright section giving you credit for all the work.

I am meeting with a teacher soon to discuss implementing a teacher schedule maker as well. This is a bit more complicated as teachers schedules change quarter to quarter however it shouldn't be a problem. We can work on this together.

What do you think?

**Comment by JRProgramming** [comment]
I like the ideas. I’m on the board for the computer club, and we do have some programmers who are totally capable of this project, so if you want to join us, just let me know (the board members meet Wednesdays before the club fair).

I do agree that if we were to combine, I would bring my site to yours. However, I do believe there should be some changes to yours. Simplicity should be the theme, so cluttering with too much words might not be ideal for people who are new to this. Plus I believe there should be some features that should be removed, but I’ll mention that later. If we can achieve this, then I think this would benefit everyone.

I am also interested in implementing a teacher schedule. It would be nice to know who is this teacher since I have also gotten some interests from other teachers.

Just one question, why do you have your site run on a server? If it has to do with downloading schedule or something like that, then that makes sense but I don’t see the purpose of that

Other than that, I think this could work.

**Comment by jbis9051** [comment]
> I’m on the board for the computer club, and we do have some programmers who are totally capable of this project

The only people I know of are @Allen-B1 (https://github.com/Allen-B1) and you. Are there others? Do any know Node.js, express, iCal files, ejs, etc.? If not, you guys can just work on the basic HTML/CSS/JS and I'll deal with the other stuff.

>  However, I do believe there should be some changes to yours. Simplicity should be the theme, so cluttering with too much words might not be ideal for people who are new to this.

Do you mean it is too complicated/cluttered for users or for developers?

If users, yeah we can remove the text on top.

> I am also interested in implementing a teacher schedule. It would be nice to know who is this teacher since I have also gotten some interests from other teachers.

Will talk next gym class.

> Just one question, why do you have your site run on a server? If it has to do with downloading schedule or something like that, then that makes sense but I don’t see the purpose of that

Every site has to run off a server. If you are asking why the HTML and schedule file are generated server side, there are two reasons:

1. I am lazy 😁. I made the module that processes schedules with Node so it cant be run in the browser without using browserify. I have never used browserify and I was too lazy to learn it so I did it server side.

2. I don't have to worry about JavaScript implementation inconsistencies in browser. It supports just about every modern browser. The calendar file would somehow have to be generated with blob's and I'm 100% how well it would work.

3. (not a real reason) I originally wasn't going to make it open source so I didn't want the code client side and assessable to anyone

> Plus I believe there should be some features that should be removed, but I’ll mention that later.

What do you suggest we remove?

**Comment by JRProgramming** [comment]
A guy named Bryant is also on the board but he doesn’t really know too much about coding so he will worry about some other stuff. Allen and I are co-presidents, so we can introduce it to him next meeting if you want. You can ask Allen what he knows, but I don’t know any of the server side stuff since I can’t pay to get lessons that are actually good.

Yeah I believe removing some texts and some features that I believe are unnecessary, but we can talk later at gym.

I’m pretty busy tonight and probably for the next few weeks so I can’t do anything code related as of now but if you’re interested in joining our meeting, we can get some help from Allen.

**Comment by jbis9051** [comment]
Please note: If you want to go through the computer club, I don't want the quality of the product to suffer to improve the educational value of developing it.

**Comment by JRProgramming** [comment]
Don’t worry, just Allen and I would work on it. And Allen knows more so there shouldn’t be any suffering

**Comment by jbis9051** [comment]
Allen, based on his github history, seems to know a lot, but not necessarily about node. I'm sure his skills would transfer with a bit of an explanation.

**Comment by JRProgramming** [comment]
Yeah just be available on Wednesday after school (2:20-2:40, will let you know and room #) and see what he knows and what he can contribute. Not sure if he wants to do it or not, but introducing this to him won’t hurt.

**Comment by JRProgramming** [comment]
Hey,

We realized club fair is on Thursday so we are going to be creating a poster for it tomorrow. We don’t know how long it would take, but feel free to check in at Mr. G’s room at 2:40 to see if we are finished and ready to discuss the site. If not, then we can set a later time to meet.

**Comment by jbis9051** [comment]
I'd like to get colors done soon if possible. When can we meet?

**Comment by JRProgramming** [comment]
Hey,

I made a pull request for the color feature only. Fix anything you need, but I haven’t tested anything yet so just be aware of that. Let me know if you can merge.
